version: "3"

services:
  auth-service:
    build:
      context: ./../sidita-auth-service
      dockerfile: ./../sidita-auth-service/auth-service.dockerfile
    restart: always
    ports:
      - "10.66.66.2:8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  project-service:
    build:
      context: ./../sidita-project-service
      dockerfile: ./../sidita-project-service/project-service.dockerfile
    restart: always
    ports:
      - "10.66.66.2:8081:8081"
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      context: ./../sidita-logger-service
      dockerfile: ./../sidita-logger-service/logger-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
