version: '3'

services:
  auth-service:
    image: dptpusmanpro/auth-service:0.0.46
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      JWT_ISSUER: "PUSMANPRO PLN"
      JWT_AUDIENCE: "103.175.220.146"
      COOKIE_DOMAIN: "103.175.220.146"
      APP_DOMAIN: "103.175.220.146"
      LOGGER_SERVICE_PORT: "5001"
      LOGGER_SERVICE_HOST: logger-service
      DSN: "host=10.66.66.3 port=5432 user=postgres password=p05tgR3s51^d1T4 dbname=sidita-v3 sslmode=disable timezone=UTC+7 connect_timeout=5"
      # DSN: /run/secrets/dsn
      REDIS_DSN: "redis://:vDBAAwyqiEz4%2F9OupVhu59hrRk3VT4SqsrMDVKqp8E3NTv3vUJCSX4lIs8t9tcGT7rV666OFPEFZGKFw@10.66.66.3:6379/0"
      JWT_SECRET: "7E0eH-Jck1Dc2pKRdrZwEUTWbYKf2-S4rhKil_dalHF-ht2lCnrDHufZUng037tY7PNJNf_UEVd8Qqb1GgHS-lzEPK-N0pTWHMZj5U36ODeC7n13vLU0IWLh46xnkc1WWghWJz1oh4j87mNzmQjDlaQodoICaoOxglY1xbr9moE"
      SEAWEEDFS_FILER: "http://10.66.66.3:8888"
    secrets:
        - dsn

  logger-service:
    image: dptpusmanpro/logger-service:0.0.20
    deploy:
      mode: replicated
      replicas: 1
    environment:
      GRPC_PORT: "5001"
      MONGO_USER: "adminUser"
      MONGO_PASSWORD: "ZXgwB6pHmh0hVPLKAjZECSCBd9yucdTILxohUQ7QoGHrt7DwDp"
      MONGO_DB: "sidita"
      MONGO_DSN: "mongodb://adminUser:ZXgwB6pHmh0hVPLKAjZECSCBd9yucdTILxohUQ7QoGHrt7DwDp@10.66.66.3:27017/sidita?directConnection=true"#

  project-service:
    image: dptpusmanpro/project-service:0.0.82
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      JWT_ISSUER: "PUSMANPRO PLN"
      JWT_AUDIENCE: "103.175.220.146"
      COOKIE_DOMAIN: "103.175.220.146"
      APP_DOMAIN: "103.175.220.146"
      LOGGER_SERVICE_PORT: "5001"
      LOGGER_SERVICE_HOST: logger-service
      DSN: "host=10.66.66.3 port=5432 user=postgres password=p05tgR3s51^d1T4 dbname=sidita-v3 sslmode=disable timezone=UTC+7 connect_timeout=5"
      REDIS_DSN: "redis://:vDBAAwyqiEz4%2F9OupVhu59hrRk3VT4SqsrMDVKqp8E3NTv3vUJCSX4lIs8t9tcGT7rV666OFPEFZGKFw@10.66.66.3:6379/0"
      JWT_SECRET: "7E0eH-Jck1Dc2pKRdrZwEUTWbYKf2-S4rhKil_dalHF-ht2lCnrDHufZUng037tY7PNJNf_UEVd8Qqb1GgHS-lzEPK-N0pTWHMZj5U36ODeC7n13vLU0IWLh46xnkc1WWghWJz1oh4j87mNzmQjDlaQodoICaoOxglY1xbr9moE"
      SEAWEEDFS_FILER: "http://10.66.66.3:8888"

secrets:
  dsn:
    file: ./dsn.txt