# Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-cert-manager
  namespace: sidita-v3
spec:
  acme:
    email: reza.yoga@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik
# Frontend: app.sidita.id
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert-frontend
  namespace: sidita-v3
spec:
  commonName: app.sidita.id
  secretName: nginx-cert-frontend
  dnsNames:
    - app.sidita.id
  issuerRef:
    kind: Issuer
    name: letsencrypt-cert-manager
# Backend: api.sidita.id
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert-backend
  namespace: sidita-v3
spec:
  commonName: api.sidita.id
  secretName: nginx-cert-backend
  dnsNames:
    - api.sidita.id
  issuerRef:
    kind: Issuer
    name: letsencrypt-cert-manager