# Issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: sidita-v3
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: reza.yoga@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: traefik

# Frontend: app.sidita.id
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert-frontend
  namespace: sidita-v3
spec:
  commonName: app.sidita.id
  secretName: app-cert-frontend
  dnsNames:
    - app.sidita.id
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
# Backend: api.sidita.id
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert-backend
  namespace: sidita-v3
spec:
  commonName: api.sidita.id
  secretName: app-cert-backend
  dnsNames:
    - api.sidita.id
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

# ArgoCD
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  commonName: argocd.sidita.id
  secretName: argocd-cert
  dnsNames:
    - argocd.sidita.id
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer