apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: sidita-v3
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 4.4.4.4
      - 103.25.111.154
  containers:
  - name: dnsutils
    image: tutum/dnsutils
    command:
      - sleep
      - "3600"
