apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: sidita-v3
spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: dnsutils
    image: tutum/dnsutils
    command:
      - sleep
      - "3600"
