# HorizontalPodAutoscaler
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nextjs-sidita-hpa
  namespace: sidita-v3
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextjs-sidita-deployment
  # targetCPUUtilizationPercentage: 75
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
# Service
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-sidita-service
  namespace: sidita-v3
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: nextjs-sidita

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-sidita-deployment
  namespace: sidita-v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-sidita
  template:
    metadata:
      labels:
        app: nextjs-sidita
    spec:
      containers:
      - name: nextjs-sidita
        image: dptpusmanpro/uat-nextjs-sidita:932
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_API_URL
          value: https://api.sidita.id
        - name: NEXT_PUBLIC_API
          value: https://app.sidita.id
        - name: NEXT_PUBLIC_SECRET_CRYPTO
          value: sidita
        - name: NEXT_PUBLIC_WEBSOCKET_URL
          value: wss://api.sidita.id
        - name: NEXT_SHARP_PATH
          value: /tmp/node_modules/sharp
        - name: NEXTAUTH_URL
          value: https://app.sidita.id
        - name: SENTRY_PUBLIC_DNS
          value: https://773c07701f51e77babfde8fcd96a4732@o4506845836148736.ingest.us.sentry.io/4507507465125888
        - name: SENTRY_PUBLIC_TOKEN
          value: sntrys_eyJpYXQiOjE3MTk1NDY5ODAuOTU2NjEzLCJ1cmwiOiJodHRwczovL3NlbnRyeS5pbyIsInJlZ2lvbl91cmwiOiJodHRwczovL3
        - name: SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING
          value: "1"
        - name: SENTRY_IGNORE_API_RESOLUTION_ERROR
          value: "1"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /tmp/node_modules/sharp
          name: sharp-cache
        resources:
          requests:
            cpu: "128m"
            memory: "128Mi"
          limits:
            cpu: "512m"
            memory: "512Mi"
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: sharp-cache
        emptyDir: {}  # Example volume type; change if needed
