apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /opt/sidita-project/swarm.yml convert -v
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: auth-service
