apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f /opt/sidita-project/swarm.yml convert -v
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: logger-service
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logger-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f /opt/sidita-project/swarm.yml convert -v
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: logger-service
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "5001"
            - name: MONGO_DB
              value: sidita
            - name: MONGO_DSN
              value: mongodb://adminUser:ZXgwB6pHmh0hVPLKAjZECSCBd9yucdTILxohUQ7QoGHrt7DwDp@10.66.66.3:27017/sidita?directConnection=true
            - name: MONGO_PASSWORD
              value: ZXgwB6pHmh0hVPLKAjZECSCBd9yucdTILxohUQ7QoGHrt7DwDp
            - name: MONGO_USER
              value: adminUser
          image: dptpusmanpro/logger-service:0.0.20
          name: logger-service
      restartPolicy: Always
